on:
  workflow_dispatch:
    
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Doing some work..."
          sleep 3
          echo "Hello, World!"

  test-action-2:
    runs-on: ubuntu-latest
    name: Super Cool Action
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Doing some super cool work..."
          sleep 2
          echo "Goodbye, World!"